# Generated by Django 5.2.7 on 2025-11-12 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apodo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='HabitoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_final', models.DateTimeField()),
                ('lugar', models.CharField(max_length=40)),
                ('estado', models.CharField(choices=[('IN', 'Inactivo'), ('FI', 'Finalizado'), ('RE', 'Realizando'), ('CO', 'Completado')], max_length=2)),
                ('categoria', models.CharField(choices=[('DE', 'Deporte'), ('CO', 'Compromiso'), ('TR', 'Trabajo'), ('OC', 'Ocio'), ('FA', 'Familia')], max_length=2)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to='habitos.usuariomodel')),
            ],
        ),
    ]
