# Generated by Django 5.2.7 on 2025-11-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitomodel',
            name='categoria',
            field=models.CharField(choices=[('FA', 'Familia'), ('DE', 'Deporte'), ('TR', 'Trabajo'), ('CO', 'Compromiso'), ('OC', 'Ocio')], max_length=2),
        ),
        migrations.AlterField(
            model_name='habitomodel',
            name='estado',
            field=models.CharField(choices=[('CO', 'Completado'), ('FI', 'Finalizado'), ('RE', 'Realizando'), ('IN', 'Inactivo')], max_length=2),
        ),
    ]
