# Generated by Django 5.2.4 on 2025-12-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitos', '0002_alter_habitomodel_categoria_alter_habitomodel_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitomodel',
            name='categoria',
            field=models.CharField(choices=[('TR', 'Trabajo'), ('OC', 'Ocio'), ('FA', 'Familia'), ('CO', 'Compromiso'), ('DE', 'Deporte')], max_length=2),
        ),
        migrations.AlterField(
            model_name='habitomodel',
            name='estado',
            field=models.CharField(choices=[('FI', 'Finalizado'), ('CO', 'Completado'), ('RE', 'Realizando'), ('IN', 'Inactivo')], max_length=2),
        ),
    ]
